---
- name: Send Metrics to OpenTelemetry Collector
  hosts: all
  gather_facts: no
  vars:
    otel_collector_url: "http://otlp:4318/v1/metrics"
    sample_metric:
      resource:
        attributes:
          service: "my_service"
          version: "1.0"
      metrics:
        - name: "dy_test"
          description: "test"
          unit: "percent"
          value: 75
          attributes:
            dy: "test"

  tasks:
    - name: Send sample metric to OTel Collector
      uri:
        url: "{{ otel_collector_url }}"
        method: POST
        headers:
          Content-Type: application/json
        body: "{{ sample_metric | to_json }}"
        return_content: yes
      register: result

    - name: Display response from OTel Collector
      debug:
        var: result.content