---
- name: Send Metrics to OpenTelemetry Collector
  hosts: all
  environment: 
    OTEL_EXPORTER_OTLP_ENDPOINT: "otlp:4317"
    OTEL_EXPORTER_OTLP_HEADERS: "authorization=Bearer {{ otlp_token }}"
    OTEL_SERVICE_NAME: test
    ANSIBLE_OPENTELEMETRY_ENABLED: "true"
  gather_facts: no
  vars:
    otel_collector_url: "http://otlp:4318/v1/metrics"
    sample_metric:
      resource:
        attributes:
          service: "my_service"
          version: "1.0"
      metrics:
        - name: "cpu_usage"
          description: "CPU usage percentage"
          unit: "percent"
          value: 75
          attributes:
            instance_id: "i-1234567890abcdef0"

  tasks:
    - name: Send sample metric to OTel Collector
      uri:
        url: "{{ otel_collector_url }}"
        method: POST
        headers:
          Content-Type: application/json
        body: "{{ sample_metric | to_json }}"
        return_content: yes
      register: result

    - name: Display response from OTel Collector
      debug:
        var: result.content